name: Build ROM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set paths
        id: paths
        run: |
          echo "project_dir=." >> $GITHUB_OUTPUT
          echo "res_dir=./res" >> $GITHUB_OUTPUT
          echo "out_dir=./out" >> $GITHUB_OUTPUT

      - name: Prepare PNGs for SGDK (320x224 RGB + patch 8x8 noir en 0,0)
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          RES_DIR="${{ steps.paths.outputs.res_dir }}"
          shopt -s nullglob
          for img in "$RES_DIR"/*.PNG "$RES_DIR"/*.png; do
            echo "Processing $img"
            # 1) Forcer 320x224, enlever alpha, truecolor (RGB)
            convert "$img" \
              -resize 320x224\! \
              -background black -alpha remove -alpha off \
              -depth 8 -type truecolor -define png:color-type=2 \
              "$img"

            # 2) Coller un patch 8x8 noir en (0,0), écrasement brut
            convert "$img" \( -size 8x8 xc:black \) \
              -geometry +0+0 -compose Copy -composite "$img"

            # 3) Vérif : diff exact sur le carré 8x8
            DIFF=$(compare -metric AE <(convert "$img" -crop 8x8+0+0 +repage PNG:-) <(convert -size 8x8 xc:black PNG:-) null: 2>&1 || true)
            echo "Top-left 8x8 pixel-diff = ${DIFF:-NA}"
          done

      - name: Build with SGDK
        uses: addnab/docker-run-action@v3
        with:
          image: registry.gitlab.com/doragasu/docker-sgdk:v2.11
          options: -v ${{ github.workspace }}:/m68k -w /m68k
          run: |
            set -e
            PROJECT_DIR="${{ steps.paths.outputs.project_dir }}"
            OUT_DIR="${{ steps.paths.outputs.out_dir }}"

            mkdir -p src/boot/ out/
            cp /sgdk/src/boot/sega.s src/boot/sega.s
            cp /sgdk/src/boot/rom_head.c src/boot/rom_head.c

            # Compilation ROM
            make -f /sgdk/makefile.gen -j1

            echo "=== Listing out/ ==="
            ls -lh "$OUT_DIR" || true

      - name: Upload ROM artifact
        uses: actions/upload-artifact@v3
        with:
          name: megadrive-rom
          path: |
            out/*.bin
            out/*.md
            out/*.gen
