name: Build & Release SGDK ROM

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Détecte où est le projet et res/
      - name: Locate project/res folders
        id: paths
        shell: bash
        run: |
          if [ -d "Md-rer/res" ]; then
            echo "project_dir=Md-rer" >> $GITHUB_OUTPUT
            echo "res_dir=Md-rer/res" >> $GITHUB_OUTPUT
            echo "out_dir=Md-rer/out" >> $GITHUB_OUTPUT
          else
            echo "project_dir=." >> $GITHUB_OUTPUT
            echo "res_dir=res" >> $GITHUB_OUTPUT
            echo "out_dir=out" >> $GITHUB_OUTPUT
          fi
          echo "Project dir = ${{ steps.paths.outputs.project_dir }}"
          echo "Res dir     = ${{ steps.paths.outputs.res_dir }}"
          ls -la "${{ steps.paths.outputs.res_dir }}" || true

      # Prépare les PNG (320x224 truecolor) + impose une tuile 8x8 noire en (0,0)
      - name: Prepare PNGs for SGDK (320x224 RGB + 8x8 black at 0,0)
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          RES_DIR="${{ steps.paths.outputs.res_dir }}"
          shopt -s nullglob
          for img in "$RES_DIR"/*.PNG "$RES_DIR"/*.png; do
            [ -f "$img" ] || continue
            echo "Processing $img"
            convert "$img" \
              -resize 320x224\! \
              -background black -alpha remove -alpha off \
              -depth 8 -type truecolor -define png:color-type=2 \
              "$img"
            # Patch 8x8 noir en haut-gauche (écrasement brut)
            convert "$img" \( -size 8x8 xc:black \) -geometry +0+0 -compose Copy -composite "$img"
            DIFF=$(compare -metric AE <(convert "$img" -crop 8x8+0+0 +repage PNG:-) <(convert -size 8x8 xc:black PNG:-) null: 2>&1 || true)
            echo "Top-left 8x8 pixel-diff for $(basename "$img") = ${DIFF:-NA}"
          done

      # Droits d’écriture pour l’UID 1000 du conteneur SGDK
      - name: Make workspace writable for container
        run: sudo chown -R 1000:1000 "$GITHUB_WORKSPACE"

      # Build dans Docker (entrypoint shell + make)
      - name: Build with SGDK (Docker)
        uses: addnab/docker-run-action@v3
        with:
          image: registry.gitlab.com/doragasu/docker-sgdk:v2.11
          options: >
            --entrypoint /bin/sh
            -e MAKEFLAGS=
            -e GNUMAKEFLAGS=
            -v ${{ github.workspace }}:/m68k
            -w /m68k/${{ steps.paths.outputs.project_dir }}
          run: >
            -c "set -e;
            mkdir -p src/boot out;
            cp /sgdk/src/boot/sega.s src/boot/sega.s;
            cp /sgdk/src/boot/rom_head.c src/boot/rom_head.c;
            make -j1;
            echo '=== out/ listing ===';
            ls -lh ./out || true"

      # Rendre les fichiers au runner
      - name: Fix back permissions for runner
        run: sudo chown -R $USER:$USER "$GITHUB_WORKSPACE"

      # Prépare le nom de sortie (prend le 1er .bin trouvé)
      - name: Prepare ROM filename
        id: name
        shell: bash
        run: |
          OUT_DIR="${{ steps.paths.outputs.out_dir }}"
          ROM=$(find "$OUT_DIR" -maxdepth 1 -type f -name '*.bin' | head -n1 || true)
          if [ -z "$ROM" ]; then
            echo "ERREUR: Aucun .bin trouvé dans $OUT_DIR"
            ls -la "$OUT_DIR" || true
            exit 1
          fi
          echo "ROM détectée: $ROM"
          REPO="${GITHUB_REPOSITORY##*/}"
          VER="${GITHUB_REF_NAME}"
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            OUT="${REPO}-${VER}.bin"
          else
            OUT="${REPO}.bin"
          fi
          cp "$ROM" "$OUT"
          echo "outname=$OUT" >> "$GITHUB_OUTPUT"
          ls -la "$OUT"

      # Upload artifact (v4 requis)
      - name: Upload ROM artifact
        uses: actions/upload-artifact@v4
        with:
          name: rom
          path: ${{ steps.name.outputs.outname }}

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: rom
          path: .
      - name: Create GitHub Release and attach ROM
        uses: softprops/action-gh-release@v2
        with:
          files: ./*.bin
          generate_release_notes: true
